parameters:
#    acme_user.example.class: Acme\UserBundle\Example

services:
#    acme_user.example:
#        class: %acme_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    security.access.ipList_voter:
        class:      Acme\IpBundle\Security\Authorization\Voter\ClientIpVoter
        #arguments:  ["@service_container", [127.0.0.1, 217.138.33.61, ::1]]
        arguments:  ["@service_container", "@doctrine.orm.entity_manager"]
        public:     false
        tags:
            - { name: security.voter }